/*
 * BOUNDARY DATA — Background scene walkability and NPC placement
 * Generated by boundary_editor.html (MacPaint aesthetic visual editor)
 * 
 * Each scene has:
 *   - walkable[]: tiles the avatar can walk on (green in editor)
 *   - blocked[]: tiles the avatar cannot walk on (red in editor)
 *   - foreground[]: tiles where foreground objects obscure the avatar (yellow in editor)
 *   - npcs[]: NPC placements with starting positions and patrol paths
 *
 * In-game, these override the normal tile collision check for BG_SCENE tiles.
 */

window.BOUNDARY_DATA = {
  // ── Roc's Nest (bg_roc_nest) ──
  // A giant nest atop the highest peak, surrounded by clouds
  nest: {
    tileSize: 32,
    gridW: 60,
    gridH: 45,
    walkable: [
      // Nest rim (circular path around the nest bowl)
      {x:25,y:18},{x:26,y:18},{x:27,y:18},{x:28,y:18},{x:29,y:18},{x:30,y:18},{x:31,y:18},{x:32,y:18},{x:33,y:18},{x:34,y:18},
      {x:24,y:19},{x:25,y:19},{x:34,y:19},{x:35,y:19},
      {x:23,y:20},{x:24,y:20},{x:35,y:20},{x:36,y:20},
      {x:22,y:21},{x:23,y:21},{x:36,y:21},{x:37,y:21},
      {x:22,y:22},{x:37,y:22},
      {x:22,y:23},{x:37,y:23},
      {x:22,y:24},{x:37,y:24},
      {x:23,y:25},{x:36,y:25},
      {x:24,y:26},{x:35,y:26},
      {x:25,y:27},{x:26,y:27},{x:27,y:27},{x:28,y:27},{x:29,y:27},{x:30,y:27},{x:31,y:27},{x:32,y:27},{x:33,y:27},{x:34,y:27},
      // Nest bowl center (walkable but slower)
      {x:27,y:22},{x:28,y:22},{x:29,y:22},{x:30,y:22},{x:31,y:22},{x:32,y:22},
      {x:27,y:23},{x:28,y:23},{x:29,y:23},{x:30,y:23},{x:31,y:23},{x:32,y:23},
      {x:27,y:24},{x:28,y:24},{x:29,y:24},{x:30,y:24},{x:31,y:24},{x:32,y:24},
      // Approach path from cliff edge
      {x:30,y:10},{x:30,y:11},{x:30,y:12},{x:30,y:13},{x:30,y:14},{x:30,y:15},{x:30,y:16},{x:30,y:17}
    ],
    blocked: [
      // Cloud edges (all around the nest)
      {x:0,y:0},{x:1,y:0},{x:2,y:0},{x:3,y:0},{x:4,y:0},{x:5,y:0},{x:6,y:0},{x:7,y:0},{x:8,y:0},{x:9,y:0},
      {x:10,y:0},{x:11,y:0},{x:12,y:0},{x:13,y:0},{x:14,y:0},{x:15,y:0},{x:16,y:0},{x:17,y:0},{x:18,y:0},{x:19,y:0},
      {x:20,y:0},{x:21,y:0},{x:22,y:0},{x:23,y:0},{x:24,y:0},{x:25,y:0},{x:26,y:0},{x:27,y:0},{x:28,y:0},{x:29,y:0},
      {x:30,y:0},{x:31,y:0},{x:32,y:0},{x:33,y:0},{x:34,y:0},{x:35,y:0},{x:36,y:0},{x:37,y:0},{x:38,y:0},{x:39,y:0},
      {x:40,y:0},{x:41,y:0},{x:42,y:0},{x:43,y:0},{x:44,y:0},{x:45,y:0},{x:46,y:0},{x:47,y:0},{x:48,y:0},{x:49,y:0},
      {x:50,y:0},{x:51,y:0},{x:52,y:0},{x:53,y:0},{x:54,y:0},{x:55,y:0},{x:56,y:0},{x:57,y:0},{x:58,y:0},{x:59,y:0},
      // ... (full perimeter would be very long; editor generates this automatically)
      // For now, everything not in walkable is implicitly blocked by the game engine
    ],
    foreground: [
      // Nest branches that the avatar walks behind
      {x:20,y:20},{x:21,y:20},{x:22,y:20},{x:23,y:20},
      {x:36,y:20},{x:37,y:20},{x:38,y:20},{x:39,y:20},
      {x:20,y:25},{x:21,y:25},{x:22,y:25},{x:23,y:25},
      {x:36,y:25},{x:37,y:25},{x:38,y:25},{x:39,y:25},
    ],
    npcs: [
      {
        type: 'eagle',
        name: 'Great Eagle',
        x: 30, y: 23,
        patrolPath: [
          {x:28,y:22},{x:30,y:22},{x:32,y:22},{x:32,y:24},{x:30,y:24},{x:28,y:24}
        ]
      }
    ],
    returnTile: { x: 30, y: 17 }
  },

  // ── Hall of Champions (bg_hall_of_champions) ──
  // Grand trophy hall with portraits, fireplace, and rug
  champion: {
    tileSize: 32,
    gridW: 60,
    gridH: 45,
    walkable: [
      // Main hall floor (center area)
      {x:15,y:15},{x:16,y:15},{x:17,y:15},{x:18,y:15},{x:19,y:15},{x:20,y:15},{x:21,y:15},{x:22,y:15},{x:23,y:15},{x:24,y:15},
      {x:25,y:15},{x:26,y:15},{x:27,y:15},{x:28,y:15},{x:29,y:15},{x:30,y:15},{x:31,y:15},{x:32,y:15},{x:33,y:15},{x:34,y:15},
      {x:35,y:15},{x:36,y:15},{x:37,y:15},{x:38,y:15},{x:39,y:15},{x:40,y:15},{x:41,y:15},{x:42,y:15},{x:43,y:15},{x:44,y:15},
      // Rug area (slightly slower movement)
      {x:20,y:25},{x:21,y:25},{x:22,y:25},{x:23,y:25},{x:24,y:25},{x:25,y:25},{x:26,y:25},{x:27,y:25},{x:28,y:25},{x:29,y:25},
      {x:30,y:25},{x:31,y:25},{x:32,y:25},{x:33,y:25},{x:34,y:25},{x:35,y:25},{x:36,y:25},{x:37,y:25},{x:38,y:25},{x:39,y:25},
      // Entry door area
      {x:28,y:40},{x:29,y:40},{x:30,y:40},{x:31,y:40},{x:32,y:40}
    ],
    blocked: [
      // Walls (perimeter)
      // Fireplace (center-left wall)
      {x:15,y:10},{x:16,y:10},{x:17,y:10},{x:18,y:10},{x:19,y:10},
      // Portrait walls (left and right)
      // Sofa and lectern (right side)
      {x:38,y:28},{x:39,y:28},{x:40,y:28},{x:41,y:28},{x:42,y:28},
    ],
    foreground: [
      // Sofa back (avatar walks behind it)
      {x:38,y:26},{x:39,y:26},{x:40,y:26},{x:41,y:26},{x:42,y:26},
      // Lectern
      {x:44,y:28},{x:45,y:28},
    ],
    npcs: [
      {
        type: 'clerk',
        name: 'Clerk of Champions',
        x: 30, y: 18,
        patrolPath: [
          {x:28,y:18},{x:30,y:18},{x:32,y:18},{x:32,y:20},{x:30,y:20},{x:28,y:20}
        ]
      }
    ],
    returnTile: { x: 30, y: 40 }
  },

  // ── Eagle's Crag (bg_eagle_s_crag) ──
  // Mountain summit ledge with stone tower and door
  eagle_crag: {
    tileSize: 32,
    gridW: 60,
    gridH: 45,
    walkable: [
      // Ledge platform (stone tiles)
      {x:10,y:15},{x:11,y:15},{x:12,y:15},{x:13,y:15},{x:14,y:15},{x:15,y:15},{x:16,y:15},{x:17,y:15},{x:18,y:15},{x:19,y:15},
      {x:20,y:15},{x:21,y:15},{x:22,y:15},{x:23,y:15},{x:24,y:15},{x:25,y:15},{x:26,y:15},{x:27,y:15},{x:28,y:15},{x:29,y:15},
      {x:30,y:15},{x:31,y:15},{x:32,y:15},{x:33,y:15},{x:34,y:15},{x:35,y:15},{x:36,y:15},{x:37,y:15},{x:38,y:15},{x:39,y:15},
      // Tower interior (through the door)
      {x:12,y:8},{x:13,y:8},{x:14,y:8},{x:15,y:8},{x:16,y:8},{x:17,y:8},
      {x:12,y:9},{x:13,y:9},{x:14,y:9},{x:15,y:9},{x:16,y:9},{x:17,y:9},
      {x:12,y:10},{x:13,y:10},{x:14,y:10},{x:15,y:10},{x:16,y:10},{x:17,y:10},
      // Door threshold
      {x:14,y:14},{x:15,y:14},{x:16,y:14},{x:17,y:14},
      // Return path
      {x:28,y:40},{x:29,y:40},{x:30,y:40},{x:31,y:40},{x:32,y:40}
    ],
    blocked: [
      // Cliff edge (drop-off)
      // Tower walls
      {x:10,y:6},{x:11,y:6},{x:12,y:6},{x:13,y:6},{x:14,y:6},{x:15,y:6},{x:16,y:6},{x:17,y:6},{x:18,y:6},{x:19,y:6},
      {x:10,y:7},{x:19,y:7},
      {x:10,y:8},{x:19,y:8},
      {x:10,y:9},{x:19,y:9},
      {x:10,y:10},{x:19,y:10},
      {x:10,y:11},{x:11,y:11},{x:12,y:11},{x:13,y:11},{x:14,y:11},{x:15,y:11},{x:16,y:11},{x:17,y:11},{x:18,y:11},{x:19,y:11},
      // Door frame
      {x:13,y:13},{x:18,y:13},
    ],
    foreground: [
      // Tower battlements (avatar walks behind the crenellations)
      {x:10,y:5},{x:11,y:5},{x:12,y:5},{x:13,y:5},{x:14,y:5},{x:15,y:5},{x:16,y:5},{x:17,y:5},{x:18,y:5},{x:19,y:5},
      // Mossy stones on ledge edge
      {x:35,y:15},{x:36,y:15},{x:37,y:15},{x:38,y:15},{x:39,y:15},
    ],
    npcs: [
      {
        type: 'eagle',
        name: 'Great Eagle',
        x: 30, y: 23,
        patrolPath: [
          {x:28,y:22},{x:30,y:22},{x:32,y:22},{x:32,y:24},{x:30,y:24},{x:28,y:24}
        ]
      }
    ],
    returnTile: { x: 30, y: 17 }
  },

  // ── Hall of Champions (bg_hall_of_champions) ──
  // Grand trophy hall with portraits, fireplace, and rug
  champion: {
    tileSize: 32,
    gridW: 60,
    gridH: 45,
    walkable: [
      // Main hall floor (center area)
      {x:15,y:15},{x:16,y:15},{x:17,y:15},{x:18,y:15},{x:19,y:15},{x:20,y:15},{x:21,y:15},{x:22,y:15},{x:23,y:15},{x:24,y:15},
      {x:25,y:15},{x:26,y:15},{x:27,y:15},{x:28,y:15},{x:29,y:15},{x:30,y:15},{x:31,y:15},{x:32,y:15},{x:33,y:15},{x:34,y:15},
      {x:35,y:15},{x:36,y:15},{x:37,y:15},{x:38,y:15},{x:39,y:15},{x:40,y:15},{x:41,y:15},{x:42,y:15},{x:43,y:15},{x:44,y:15},
      // Rug area (slightly slower movement)
      {x:20,y:25},{x:21,y:25},{x:22,y:25},{x:23,y:25},{x:24,y:25},{x:25,y:25},{x:26,y:25},{x:27,y:25},{x:28,y:25},{x:29,y:25},
      {x:30,y:25},{x:31,y:25},{x:32,y:25},{x:33,y:25},{x:34,y:25},{x:35,y:25},{x:36,y:25},{x:37,y:25},{x:38,y:25},{x:39,y:25},
      // Entry door area
      {x:28,y:40},{x:29,y:40},{x:30,y:40},{x:31,y:40},{x:32,y:40}
    ],
    blocked: [
      // Walls (perimeter)
      // Fireplace (center-left wall)
      {x:15,y:10},{x:16,y:10},{x:17,y:10},{x:18,y:10},{x:19,y:10},
      // Portrait walls (left and right)
      // Sofa and lectern (right side)
      {x:38,y:28},{x:39,y:28},{x:40,y:28},{x:41,y:28},{x:42,y:28},
    ],
    foreground: [
      // Sofa back (avatar walks behind it)
      {x:38,y:26},{x:39,y:26},{x:40,y:26},{x:41,y:26},{x:42,y:26},
      // Lectern
      {x:44,y:28},{x:45,y:28},
    ],
    npcs: [
      {
        type: 'clerk',
        name: 'Clerk of Champions',
        x: 30, y: 18,
        patrolPath: [
          {x:28,y:18},{x:30,y:18},{x:32,y:18},{x:32,y:20},{x:30,y:20},{x:28,y:20}
        ]
      }
    ],
    returnTile: { x: 30, y: 40 }
  },

  // ── Eagle's Crag (bg_eagle_s_crag) ──
  // Mountain summit ledge with stone tower and door
  eagle_crag: {
    tileSize: 32,
    gridW: 60,
    gridH: 45,
    walkable: [
      // Ledge platform (stone tiles)
      {x:10,y:15},{x:11,y:15},{x:12,y:15},{x:13,y:15},{x:14,y:15},{x:15,y:15},{x:16,y:15},{x:17,y:15},{x:18,y:15},{x:19,y:15},
      {x:20,y:15},{x:21,y:15},{x:22,y:15},{x:23,y:15},{x:24,y:15},{x:25,y:15},{x:26,y:15},{x:27,y:15},{x:28,y:15},{x:29,y:15},
      {x:30,y:15},{x:31,y:15},{x:32,y:15},{x:33,y:15},{x:34,y:15},{x:35,y:15},{x:36,y:15},{x:37,y:15},{x:38,y:15},{x:39,y:15},
      // Tower interior (through the door)
      {x:12,y:8},{x:13,y:8},{x:14,y:8},{x:15,y:8},{x:16,y:8},{x:17,y:8},
      {x:12,y:9},{x:13,y:9},{x:14,y:9},{x:15,y:9},{x:16,y:9},{x:17,y:9},
      {x:12,y:10},{x:13,y:10},{x:14,y:10},{x:15,y:10},{x:16,y:10},{x:17,y:10},
      // Door threshold
      {x:14,y:14},{x:15,y:14},{x:16,y:14},{x:17,y:14},
      // Return path
      {x:28,y:40},{x:29,y:40},{x:30,y:40},{x:31,y:40},{x:32,y:40}
    ],
    blocked: [
      // Cliff edge (drop-off)
      // Tower walls
      {x:10,y:6},{x:11,y:6},{x:12,y:6},{x:13,y:6},{x:14,y:6},{x:15,y:6},{x:16,y:6},{x:17,y:6},{x:18,y:6},{x:19,y:6},
      {x:10,y:7},{x:19,y:7},
      {x:10,y:8},{x:19,y:8},
      {x:10,y:9},{x:19,y:9},
      {x:10,y:10},{x:19,y:10},
      {x:10,y:11},{x:11,y:11},{x:12,y:11},{x:13,y:11},{x:14,y:11},{x:15,y:11},{x:16,y:11},{x:17,y:11},{x:18,y:11},{x:19,y:11},
      // Door frame
      {x:13,y:13},{x:18,y:13},
    ],
    foreground: [
      // Tower battlements (avatar walks behind the crenellations)
      {x:10,y:5},{x:11,y:5},{x:12,y:5},{x:13,y:5},{x:14,y:5},{x:15,y:5},{x:16,y:5},{x:17,y:5},{x:18,y:5},{x:19,y:5},
      // Mossy stones on ledge edge
      {x:35,y:15},{x:36,y:15},{x:37,y:15},{x:38,y:15},{x:39,y:15},
    ],
    npcs: [
      {
        type: 'eagle',
        name: 'Hungry Eagle',
        x: 25, y: 16,
        patrolPath: [
          {x:22,y:16},{x:25,y:16},{x:28,y:16},{x:28,y:18},{x:25,y:18},{x:22,y:18}
        ]
      }
    ],
    returnTile: { x: 30, y: 40 }
  }
};
